---

- hosts: localhost
  gather_facts: False
  tasks:

    ############################################################################
    - name: Register {{ dataspectsSystem_control_folder_on_host | basename | lower }}_mediawiki_root path on host
      shell: docker volume inspect {{ dataspectsSystem_control_folder_on_host | basename | lower }}_mediawiki_root
      register: volume_profile
      tags:
        - install_mediawiki
        - t1811161102t
    - set_fact: mountpoint={{ dict(volume_profile.stdout | from_json | json_query('[].[Name,Mountpoint]')) }}
      tags:
        - install_mediawiki
        - t1811161102t
    ############################################################################

    - name: Clone required mediawiki version
      shell: "git clone -b {{ mediawiki_version }} --depth 1 --single-branch https://github.com/wikimedia/mediawiki.git w/"
      args:
        chdir: "{{ mountpoint.items()[0][1] }}"
      become: true
      tags:
        - install_mediawiki

    - name: Install core extensions and skins
      shell: "git submodule update --init --recursive"
      args:
        chdir: "{{ mountpoint.items()[0][1] }}/w/"
      become: true
      tags:
        - install_mediawiki

    - name: Place composer install script
      template:
        src: ../ansible_templates/install_composer.sh
        dest: "{{ mountpoint.items()[0][1] }}/w/install_composer.sh"
        mode: 0777
      become: true
      tags:
        - install_mediawiki

    - name: Install composer locally
      shell: docker exec {{ dataspectsSystem_control_folder_on_host | basename | lower }}_{{ mediawikiDockerServiceName }}_1 bash -c "cd /var/www/html/w && ./install_composer.sh"
      tags:
        - install_mediawiki

    # [[IsOperationType::VendorPackageOperation]]
    - name: Run composer inside container
      shell: docker exec {{ dataspectsSystem_control_folder_on_host | basename | lower }}_{{ mediawikiDockerServiceName }}_1 bash -c "cd /var/www/html/w && php composer.phar install"
      tags:
        - install_mediawiki

    # [[IsOperationType::FileSystemOperation]]
    - name: Place mediawiki install script
      template:
        src: ../ansible_templates/install_mediawiki.sh.j2
        dest: "{{ mountpoint.items()[0][1] }}/w/install.sh"
        mode: 0777
      become: true
      tags:
        - install_mediawiki

    # [[IsOperationType::VendorPackageOperation]]
    - name: Install mediawiki inside container
      shell: "docker exec {{ dataspectsSystem_control_folder_on_host | basename | lower }}_{{ mediawikiDockerServiceName }}_1 bash -c 'cd /var/www/html/w && ./install.sh'"
      tags:
        - install_mediawiki

    - name: Add settings to LocalSettings.php
      lineinfile:
        path: "{{ mountpoint.items()[0][1] }}/w/LocalSettings.php"
        line: "{{ item }}"
      with_items:
        - $wgArticlePath = '/wiki/$1';
        - $wgFileExtensions[] = 'pdf';
      become: true
      tags:
        - install_mediawiki

    #FIXME: This should replace, but it actually just adds!
    - name: Replace settings in LocalSettings.php
      lineinfile:
        path: "{{ mountpoint.items()[0][1] }}/w/LocalSettings.php"
        regexp: '{{ item.orig }}'
        line: '{{ item.replace }}'
      with_items:
        - { orig: "^$wgServer = ", replace: '$wgServer = "http://local.mediawiki";' }
        - { orig: "^$wgEnableUploads = ", replace: '$wgEnableUploads = true;' }
      become: true
      tags:
        - install_mediawiki
        - t1811161102t

    # [[IsOperationType::VendorPackageOperation]]
    - name: Change admin user password
      shell: docker exec {{ dataspectsSystem_control_folder_on_host | basename | lower }}_{{ mediawikiDockerServiceName }}_1 bash
               -c "cd /var/www/html/w/maintenance &&
                   php changePassword.php --user='admin' --password='{{ mediawiki_admin_user_password }}'"
      become: true
      tags:
        - install_mediawiki

    #FIXME: This should replace, but it actually just adds!
    - name: Replace settings in LocalSettings.php
      lineinfile:
        path: "{{ mountpoint.items()[0][1] }}/w/LocalSettings.php"
        regexp: '{{ item.orig }}'
        line: '{{ item.replace }}'
      with_items:
        - { orig: "^$wgServer = ", replace: '$wgServer = "http://{{ mediawikiDomainNameInHostFile }}:{{ nginxPortOnHost }}";' }
        - { orig: "^$wgEnableUploads = ", replace: '$wgEnableUploads = true;' }
      become: true
      tags:
        - install_mediawiki

    # [[IsOperationType::FileSystemOperation]]
    - name: Set permissions on mediawiki root
      file:
        path: "{{ mountpoint.items()[0][1] }}/w/"
        owner: www-data
        recurse: yes
      become: true
      tags:
        - install_mediawiki

    ############################################################################
    # configure_proxy ##########################################################
    - name: Register {{ dataspectsSystem_control_folder_on_host | basename | lower }}_nginx_conf path on host
      shell: docker volume inspect {{ dataspectsSystem_control_folder_on_host | basename | lower }}_nginx_conf
      register: volume_profile
      tags:
        - configure_proxy
    - set_fact: mountpoint={{ dict(volume_profile.stdout | from_json | json_query('[].[Name,Mountpoint]')) }}
      tags:
        - configure_proxy

    - name: Place mediawiki service nginx conf
      template:
        src: ../ansible_templates/mediawiki-nginx.conf.j2
        dest: "{{ mountpoint.items()[0][1] }}/mediawiki-nginx.conf"
        mode: 0777
      become: true
      tags:
        - configure_proxy

    - name: Restart Nginx Proxy
      shell: docker-compose \
               --file {{ dataspectsSystem_control_folder_on_host }}/docker-compose.yml \
                 restart proxy
      tags:
        - configure_proxy
